# Generated by Django 3.2.5 on 2021-08-03 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_addon_order_producebox_snackbox'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddOn',
            new_name='Product',
        ),
        migrations.DeleteModel(
            name='ProduceBox',
        ),
        migrations.DeleteModel(
            name='SnackBox',
        ),
    ]
