# Generated by Django 3.1.1 on 2021-01-23 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_mission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='name',
        ),
    ]
