# Generated by Django 3.1.1 on 2021-06-26 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mission',
        ),
    ]
