# Generated by Django 3.2.5 on 2021-08-31 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_cartitem_lineitem'),
        ('pages', '0005_delete_mission'),
    ]

    operations = [
    ]
